<?php

namespace ContainerRVfkjj7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A1pPcp8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A1pPcp8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A1pPcp8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'privateCustomer' => ['privates', '.errored..service_locator.A1pPcp8.App\\Entity\\PrivateCustomer', NULL, 'Cannot autowire service ".service_locator.A1pPcp8": it needs an instance of "App\\Entity\\PrivateCustomer" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'privateCustomer' => 'App\\Entity\\PrivateCustomer',
        ]);
    }
}
