<?php

namespace ContainerRVfkjj7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OR1X6haService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OR1X6ha' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OR1X6ha'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'vehicleRepository' => ['privates', 'App\\Repository\\VehicleRepository', 'getVehicleRepositoryService', true],
        ], [
            'paginator' => '?',
            'vehicleRepository' => 'App\\Repository\\VehicleRepository',
        ]);
    }
}
