<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Provider extends \App\Entity\Provider implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'LOPDdoc' => [parent::class, 'LOPDdoc', null],
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'bankTitle' => [parent::class, 'bankTitle', null],
        "\0".parent::class."\0".'businessName' => [parent::class, 'businessName', null],
        "\0".parent::class."\0".'cif' => [parent::class, 'cif', null],
        "\0".parent::class."\0".'constitutionArticle' => [parent::class, 'constitutionArticle', null],
        "\0".parent::class."\0".'dni' => [parent::class, 'dni', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'managerNif' => [parent::class, 'managerNif', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'vehicles' => [parent::class, 'vehicles', null],
        'LOPDdoc' => [parent::class, 'LOPDdoc', null],
        'address' => [parent::class, 'address', null],
        'bankTitle' => [parent::class, 'bankTitle', null],
        'businessName' => [parent::class, 'businessName', null],
        'cif' => [parent::class, 'cif', null],
        'constitutionArticle' => [parent::class, 'constitutionArticle', null],
        'dni' => [parent::class, 'dni', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'managerNif' => [parent::class, 'managerNif', null],
        'phone' => [parent::class, 'phone', null],
        'vehicles' => [parent::class, 'vehicles', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
