<?php

namespace ContainerX94UA0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrivateCustomerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A1pPcp8.App\Entity\PrivateCustomer' shared service.
     *
     * @return \App\Entity\PrivateCustomer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.A1pPcp8": it needs an instance of "App\\Entity\\PrivateCustomer" but this type has been excluded in "config/services.yaml".');
    }
}
