<?php

namespace ContainerZljF9aZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U5CX0jjService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.u5CX0jj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u5CX0jj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'privateCustomer' => ['privates', '.errored..service_locator.u5CX0jj.App\\Entity\\PrivateCustomer', NULL, 'Cannot autowire service ".service_locator.u5CX0jj": it needs an instance of "App\\Entity\\PrivateCustomer" but this type has been excluded in "config/services.yaml".'],
        ], [
            'privateCustomer' => 'App\\Entity\\PrivateCustomer',
        ]);
    }
}
