<?php

namespace ContainerZljF9aZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9ympnmOService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.9ympnmO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9ympnmO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'professional' => ['privates', '.errored..service_locator.9ympnmO.App\\Entity\\Professional', NULL, 'Cannot autowire service ".service_locator.9ympnmO": it needs an instance of "App\\Entity\\Professional" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'professional' => 'App\\Entity\\Professional',
        ]);
    }
}
