<?php

namespace ContainerZljF9aZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProvider2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iK13U2p.App\Entity\Provider' shared service.
     *
     * @return \App\Entity\Provider
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iK13U2p": it needs an instance of "App\\Entity\\Provider" but this type has been excluded in "config/services.yaml".');
    }
}
