<?php

namespace ContainerZljF9aZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrivateCustomer2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.u5CX0jj.App\Entity\PrivateCustomer' shared service.
     *
     * @return \App\Entity\PrivateCustomer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.u5CX0jj": it needs an instance of "App\\Entity\\PrivateCustomer" but this type has been excluded in "config/services.yaml".');
    }
}
