<?php

namespace ContainerZljF9aZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfessional2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ddcvPQZ.App\Entity\Professional' shared service.
     *
     * @return \App\Entity\Professional
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ddcvPQZ": it needs an instance of "App\\Entity\\Professional" but this type has been excluded in "config/services.yaml".');
    }
}
