<?php

namespace ContainerZljF9aZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrivateCustomerTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\PrivateCustomerType' shared autowired service.
     *
     * @return \App\Form\PrivateCustomerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PrivateCustomerType.php';

        return $container->privates['App\\Form\\PrivateCustomerType'] = new \App\Form\PrivateCustomerType();
    }
}
