<?php

namespace ContainerZljF9aZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrivateCustomerControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\PrivateCustomerController' shared autowired service.
     *
     * @return \App\Controller\PrivateCustomerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PrivateCustomerController.php';

        $container->services['App\\Controller\\PrivateCustomerController'] = $instance = new \App\Controller\PrivateCustomerController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PrivateCustomerController', $container));

        return $instance;
    }
}
