<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZljF9aZ\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZljF9aZ/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerZljF9aZ.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerZljF9aZ\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerZljF9aZ\App_KernelTestDebugContainer([
    'container.build_hash' => 'ZljF9aZ',
    'container.build_id' => 'f7c81d5d',
    'container.build_time' => 1706007688,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZljF9aZ');
