<?php

namespace ContainerSBvcDHp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YyODij6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YyODij6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YyODij6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\InvoiceController::delete' => ['privates', '.service_locator.6WVeyEx', 'get_ServiceLocator_6WVeyExService', true],
            'App\\Controller\\InvoiceController::edit' => ['privates', '.service_locator.6WVeyEx', 'get_ServiceLocator_6WVeyExService', true],
            'App\\Controller\\InvoiceController::index' => ['privates', '.service_locator.yNJ0lDi', 'get_ServiceLocator_YNJ0lDiService', true],
            'App\\Controller\\InvoiceController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\InvoiceController::show' => ['privates', '.service_locator.8uD4.Hd', 'get_ServiceLocator_8uD4_HdService', true],
            'App\\Controller\\OrderController::delete' => ['privates', '.service_locator.EDFwMy7', 'get_ServiceLocator_EDFwMy7Service', true],
            'App\\Controller\\OrderController::edit' => ['privates', '.service_locator.EDFwMy7', 'get_ServiceLocator_EDFwMy7Service', true],
            'App\\Controller\\OrderController::index' => ['privates', '.service_locator.4n4ylFv', 'get_ServiceLocator_4n4ylFvService', true],
            'App\\Controller\\OrderController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\OrderController::show' => ['privates', '.service_locator.ruxHxcA', 'get_ServiceLocator_RuxHxcAService', true],
            'App\\Controller\\ProviderController::delete' => ['privates', '.service_locator.iK13U2p', 'get_ServiceLocator_IK13U2pService', true],
            'App\\Controller\\ProviderController::edit' => ['privates', '.service_locator.iK13U2p', 'get_ServiceLocator_IK13U2pService', true],
            'App\\Controller\\ProviderController::index' => ['privates', '.service_locator.bPn_kN7', 'get_ServiceLocator_BPnKN7Service', true],
            'App\\Controller\\ProviderController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProviderController::show' => ['privates', '.service_locator.VXJivNX', 'get_ServiceLocator_VXJivNXService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\InvoiceController:delete' => ['privates', '.service_locator.6WVeyEx', 'get_ServiceLocator_6WVeyExService', true],
            'App\\Controller\\InvoiceController:edit' => ['privates', '.service_locator.6WVeyEx', 'get_ServiceLocator_6WVeyExService', true],
            'App\\Controller\\InvoiceController:index' => ['privates', '.service_locator.yNJ0lDi', 'get_ServiceLocator_YNJ0lDiService', true],
            'App\\Controller\\InvoiceController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\InvoiceController:show' => ['privates', '.service_locator.8uD4.Hd', 'get_ServiceLocator_8uD4_HdService', true],
            'App\\Controller\\OrderController:delete' => ['privates', '.service_locator.EDFwMy7', 'get_ServiceLocator_EDFwMy7Service', true],
            'App\\Controller\\OrderController:edit' => ['privates', '.service_locator.EDFwMy7', 'get_ServiceLocator_EDFwMy7Service', true],
            'App\\Controller\\OrderController:index' => ['privates', '.service_locator.4n4ylFv', 'get_ServiceLocator_4n4ylFvService', true],
            'App\\Controller\\OrderController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\OrderController:show' => ['privates', '.service_locator.ruxHxcA', 'get_ServiceLocator_RuxHxcAService', true],
            'App\\Controller\\ProviderController:delete' => ['privates', '.service_locator.iK13U2p', 'get_ServiceLocator_IK13U2pService', true],
            'App\\Controller\\ProviderController:edit' => ['privates', '.service_locator.iK13U2p', 'get_ServiceLocator_IK13U2pService', true],
            'App\\Controller\\ProviderController:index' => ['privates', '.service_locator.bPn_kN7', 'get_ServiceLocator_BPnKN7Service', true],
            'App\\Controller\\ProviderController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProviderController:show' => ['privates', '.service_locator.VXJivNX', 'get_ServiceLocator_VXJivNXService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\InvoiceController::delete' => '?',
            'App\\Controller\\InvoiceController::edit' => '?',
            'App\\Controller\\InvoiceController::index' => '?',
            'App\\Controller\\InvoiceController::new' => '?',
            'App\\Controller\\InvoiceController::show' => '?',
            'App\\Controller\\OrderController::delete' => '?',
            'App\\Controller\\OrderController::edit' => '?',
            'App\\Controller\\OrderController::index' => '?',
            'App\\Controller\\OrderController::new' => '?',
            'App\\Controller\\OrderController::show' => '?',
            'App\\Controller\\ProviderController::delete' => '?',
            'App\\Controller\\ProviderController::edit' => '?',
            'App\\Controller\\ProviderController::index' => '?',
            'App\\Controller\\ProviderController::new' => '?',
            'App\\Controller\\ProviderController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\InvoiceController:delete' => '?',
            'App\\Controller\\InvoiceController:edit' => '?',
            'App\\Controller\\InvoiceController:index' => '?',
            'App\\Controller\\InvoiceController:new' => '?',
            'App\\Controller\\InvoiceController:show' => '?',
            'App\\Controller\\OrderController:delete' => '?',
            'App\\Controller\\OrderController:edit' => '?',
            'App\\Controller\\OrderController:index' => '?',
            'App\\Controller\\OrderController:new' => '?',
            'App\\Controller\\OrderController:show' => '?',
            'App\\Controller\\ProviderController:delete' => '?',
            'App\\Controller\\ProviderController:edit' => '?',
            'App\\Controller\\ProviderController:index' => '?',
            'App\\Controller\\ProviderController:new' => '?',
            'App\\Controller\\ProviderController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
