<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX94UA0x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX94UA0x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX94UA0x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX94UA0x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX94UA0x\App_KernelDevDebugContainer([
    'container.build_hash' => 'X94UA0x',
    'container.build_id' => '5689cb6f',
    'container.build_time' => 1706007756,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX94UA0x');
