<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSBvcDHp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSBvcDHp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSBvcDHp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSBvcDHp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSBvcDHp\App_KernelDevDebugContainer([
    'container.build_hash' => 'SBvcDHp',
    'container.build_id' => 'd477d458',
    'container.build_time' => 1704878831,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSBvcDHp');
